### ISSUE TITLE
E2ETest setup

### ISSUE THREAD

**Issue by joshbaskaran** [ELIXIR-NO/FEGA-Norway#83] opened 2024-02-07 09:18 UTC
Adds the necessary configs to start the migration of end-2-end tests into the monorepo.

**Comment by joshbaskaran** [comment] 2024-02-14 08:44
This should be considered complete once the "integration test" from the localega-deploy-swarm-fork has been successfully moved in and confirmed to be working.

**Comment by yasinmiran** [comment] 2024-03-13 16:38
### Progress update:

We've attempted to load certificates and the necessary configuration files into our containers using Docker volume mappings. However, we encountered issues with certain containers requiring specific user/group ownership and permissions for some files.

> Context: Previously, to deploy the EGA stack, we utilized Docker Swarm and a stack file where we defined secrets [0], as shown in [1], and utilized them in our services. This approach worked seamlessly with Docker Swarm. Additionally, we used volumes to map the configuration files [2].

So far, we've explored the following methods to load certificates and configurations:

1. Secrets
2. Configs
3. Volume mappings

All these methods successfully transfer the files to the desired destination, but none offer file permission granularity (such as setting `uid`, `gid`, and `mode`) when using Docker Compose.

After extensively reviewing the official documentation, I found it somewhat misleading. If you check [3][4] you will see that it suggests that configs and secrets operate similarly, except for a note that says `... secret's lifecycle is not directly managed by Compose`. According to a comment in a discussion [5], secrets and configs partially work because Docker internally binds the source to the target but ignores other supposed properties.

#### My findings indicate that:

- `configs` and `secrets` do not support properties in the "long syntax."
- `volumes` lacks support for file permission granularity.

#### Considering alternative approaches:

1. Using an **entry point script** has been somewhat effective (kind of).
2. **Volume mounts with uid:gid mappings preserved on the host** work but are not ideal due to the requirement for full sudo access, which complicates the automation script (but this is doable)
3. **Overriding the default command**, such as adjusting the user:group for RabbitMQ with a shell command, poses challenges. Firstly, Docker maps volume directories and files as symbolic links. Secondly, the sda images lack shell applications (mapper,verify,ingest,finalize), only containing direct executables.
i.e., `sh -c "chmod -R 0644 /etc/rabbitmq/conf/* && chown -R 100:101 /etc/rabbitmq/conf/* && rabbitmq-server"`

[0] https://github.com/uio-bmi/LocalEGA-deploy-swarm-fork/blob/7b7d09105522458b97a2c31dc4c566290f763850/docker-template.yml#L496-L522

[1] https://github.com/uio-bmi/LocalEGA-deploy-swarm-fork/blob/7b7d09105522458b97a2c31dc4c566290f763850/docker-template.yml#L445-L457

[2] https://github.com/uio-bmi/LocalEGA-deploy-swarm-fork/blob/7b7d09105522458b97a2c31dc4c566290f763850/docker-template.yml#L458-L461

[3] https://docs.docker.com/compose/compose-file/05-services/#configs

[4]https://docs.docker.com/compose/compose-file/05-services/#secrets 

[5] https://github.com/docker/compose/issues/9648#issuecomment-1852701204

[6] https://github.com/docker/compose/issues/9648

**Comment by yasinmiran** [comment] 2024-03-14 16:31
So far, we've managed to run all the other images except for `mq-interceptor` and `sda-stack` (`ingest`, `verify`, `sda-finalize`, `sda-mapper`)

**Did we solve the permissions and ownership issues yet?**
No, not yet. we tried to do volume mappings with `uid:gid` mappings with several approaches and we still run into `sudo` issues during the script execution. Since, the certificate generation is a part of the Gradle build process we don't have the luxury to run sudo commands within command line operations. We've also tried to create a custom Dockerfile for sda-stack and avoid distroless images but that solution is dirty and complicates things a lot.

After hours of trying I manually set `nobody:nogroup` to all the files and proceed further (this is not what we want but at this point we have to see what other obstacles we have getting the stack up and running).

Then we ran into another issue. See the following logs:

Here's some local logs from the `sda-ingest` (all the containers complaint the same including `mq-interceptor`):

```
time="2024-03-14T16:03:07Z" level=info msg="reading config"
time="2024-03-14T16:03:07Z" level=info msg="Config File \"config\" Not Found in \"[/]\""
time="2024-03-14T16:03:07Z" level=info msg="No config file found, using ENVs only"
time="2024-03-14T16:03:07Z" level=info msg="Setting log level to 'debug'"
time="2024-03-14T16:03:07Z" level=debug msg="Connecting to broker host: mq:5671 vhost: /test with user: admin"
time="2024-03-14T16:03:07Z" level=error msg="dial tcp: lookup mq on 127.0.0.11:53: server misbehaving"
time="2024-03-14T16:03:07Z" level=fatal msg="Could not recover, exiting"

```

The problem seems to be DNS configurations in Docker. So we've added a custom network configuration to our services. Still, we ge tthe same lookup errors. Then I tried changing the default DNS resolving `namespace` to Google's public DNS `8.8.8.8` in `/etc/resolv.conf` but still, the issue persists. Currently looking into how we can resolve this issue.

**Comment by yasinmiran** [comment] 2024-04-08 16:45
## Progress Update

We've decided to disable TLS connections within our services to focus on setting up end-to-end testing.

The latest testing-related changes are included in the following branch [feat/add-java-tests-2](https://github.com/ELIXIR-NO/FEGA-Norway/tree/feat/add-java-tests-2). I have thoroughly reviewed and revised all configurations.

Despite disabling TLS, I encountered an issue where the `mq-interceptor` could not properly connect to MQ. After hours of debugging, I discovered that the problem wasn't related to certificates, as initially suspected. The real issue was the startup time of the RabbitMQ server.

Our RabbitMQ service instance uses several management plugins. Here's the command used to start the container:
```bash
command: sh -c "rabbitmq-plugins enable --offline rabbitmq_federation rabbitmq_federation_management rabbitmq_shovel rabbitmq_shovel_management && rabbitmq-server"
```

It takes about `3-5` seconds for the server to fully start. However, Docker Compose begins to spin up other containers immediately after executing the `sh` command, resulting in an additional 3 seconds for RabbitMQ to fully start. As a result, Docker Compose starts all dependent components too early.

To ensure compatibility with both Swarm and Compose, I made modifications to the service code. I implemented a retry mechanism with intervals for establishing connections to MQ and `cegamq` instances.

```go
// dialRabbitMQ attempts to connect to RabbitMQ up to 10 times
// with a delay between retries. It returns a connection
// instance or an error.
func dialRabbitMQ(connectionString string) (*amqp.Connection, error) {
	var conn *amqp.Connection
	var err error
	var attempts = 10
	// Parse the connection string as a URL.
	u, err := url.Parse(connectionString)
	if err != nil {
		return nil, err
	}
	log.Printf("Trying to dial host: %s [I will attempt to dial %d times with 2 seconds interval]", u.Hostname(), attempts)
	log.Printf("Is TLS enabled? %t", os.Getenv("ENABLE_TLS") == "true")
	for i := 0; i < attempts; i++ {
		if os.Getenv("ENABLE_TLS") == "true" {
			conn, err = amqp.DialTLS(connectionString, getTLSConfig())
		} else {
			conn, err = amqp.Dial(connectionString)
		}
		if err == nil {
			log.Printf("Successfully connected to %s\n", connectionString)
			return conn, nil
		}
		log.Printf("Attempt %d: Failed to connect to RabbitMQ: %s\n", i+1, err)
		time.Sleep(2 * time.Second) // Wait before retrying
	}
	// After all attempts, return the last error
	return nil, err
}
```

Now, everything connects successfully. However, intermittently (after about 7 to 10 minutes), the interceptor crashes with the following error log:

```txt
± |feat/add-java-tests-2 {2} ?:1 ✗| → docker logs interceptor 
2024/04/08 15:05:15 Trying to dial host: mq [I will attempt to dial 10 times with 2 seconds interval]
2024/04/08 15:05:15 Is TLS enabled? false
2024/04/08 15:05:15 Attempt 1: Failed to connect to RabbitMQ: dial tcp 172.21.0.4:5672: connect: connection refused
2024/04/08 15:05:17 Attempt 2: Failed to connect to RabbitMQ: dial tcp 172.21.0.4:5672: connect: connection refused
2024/04/08 15:05:19 Attempt 3: Failed to connect to RabbitMQ: dial tcp 172.21.0.4:5672: connect: connection refused
2024/04/08 15:05:21 Successfully connected to amqp://admin:guest@mq:5672/test
2024/04/08 15:05:21 Trying to dial host: cegamq [I will attempt to dial 10 times with 2 seconds interval]
2024/04/08 15:05:21 Is TLS enabled? false
2024/04/08 15:05:21 Successfully connected to amqp://test:test@cegamq:5673/lega
2024/04/08 15:05:21  [*] Waiting for messages. To exit press CTRL+C
2024/04/08 15:12:36 Exception (501) Reason: "read tcp 172.21.0.8:53264->172.21.0.4:5672: i/o timeout"
```

At this moment, the cause of these intermittent disconnections is unclear. Even after adjusting the RabbitMQ server heartbeat to a 1-minute interval, the issue persists. Aside from this singular problem, every container operates error-free and remains up and running.

**Closed** 2024-05-02 07:24 UTC
Labels: test
